baseURL = 'https://kilpkonn.github.io/learn-shortcuts/'
languageCode = 'en-us'
title = 'Learn Shortcuts'
theme = 'hugo-book'
publishdir = "docs"


[markup.goldmark.renderer]
  unsafe = true

[params]
 BookMenuBundle = '/menu'
